repos:
  - repo: local
    hooks:
      - id: black
        name: Formatting code (black)
        entry: black
        language: system
        types: [python]
      - id: flake8
        name: Enforcing pep8 (flake8)
        entry: flake8
        language: system
        types: [python]
      - id: isort
        name: Sorting imports (isort)
        entry: isort
        language: system
        types: [python]