name: Mente do mestre
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          pip install -r requirements.test.txt

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
